# yaml-language-server: $schema=../vendor/symfony/routing/Loader/schema/routing.schema.json

# This file is the entry point to configure the routes of your app.
# Methods with the #[Route] attribute are automatically imported.
# See also https://symfony.com/doc/current/routing.html

# To list all registered routes, run the following command:
#   bin/console debug:router

app_default:
    path: /
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::redirectAction
    defaults:
        route: app_login
        permanent: false

app_login:
    path: /login
    methods: [GET]
    controller: App\Controller\AuthController::index

app_login_submit: 
    path: /login
    methods: [POST]
    controller: App\Controller\AuthController::connectUser

app_register:
    path: /register
    methods: [GET]
    controller: App\Controller\AuthController::register

app_register_submit:
    path: /register
    methods: [POST]
    controller: App\Controller\AuthController::createUser

app_home:
    path: /home
    controller: App\Controller\HomeController::index

app_logout: 
    path: /logout
    controller : App\Controller\HomeController::logout

app_mailCheck: 
    path: /mailCheck/{id}
    methods: [GET]
    controller : App\Controller\MailController::mailVerification

app_mailCheck_post: 
    path: /mailCheck/{id}
    methods: [POST]
    controller : App\Controller\MailController::checkCode

app_resetPassword:
    path: /resetpassword
    methods: [GET, POST]
    controller : App\Controller\MailController::resetPassword

app_resetPassword_post: 
    path: /resetpassword
    methods: [POST]
    controller : App\Controller\MailController::resetPassword_post

app_newPassword:
    path: /newpassword/{token}
    methods: [GET, POST]
    controller : App\Controller\MailController::newPassword
